import type { Metadata } from "next";
import { Manrope, Outfit, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import ClientProvider from "@/components/ClientProvider";
import Header from "@/components/Header/Header";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // optional but recommended
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // optional but recommended
});

export const metadata: Metadata = {
  title: "Neighbourly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${outfit.variable} ${poppins.variable} antialiased`}
        suppressHydrationWarning={true}
      >

        <ClientProvider>
          <div className="bg-white  shadow-2xl shadow-heading1">
            <Header />
          </div>
          {children}

        </ClientProvider>
        <Footer />
      </body>
    </html>
  );
}
